### ISSUE TITLE
What would be best way to have plugin just create a single render?

### ISSUE THREAD

**Issue by ForceConstant** [ukdavewood/Blender-Multicolour-GCode-Importer#1]
I am more intersted in using this plugin to create a static render, instead of a timelapse, to be used as a show off picture of a model, to go along with actual printed pictures.  Maybe there is a companion script that creates a basic table or renderable desk, and then show the imported gcode model on top of it.

**Comment by ukdavewood** [comment]
The easiest way it to just move to the end of the timeline.  

The script is primarily designed for animating the 3d printing process - but it should be fairly easy to add things like desks etc into the file - either before or after the import is run.
